package guis;

import applic_datamining.JApplic_Chat;
import Outils.FichierLog;
import Outils.LibrairieJDBC;
import RequeteReponseFECOP.*;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class FenetreLogin extends javax.swing.JDialog {

    private JApplic_Chat fenetreClient;
    public Socket cliSock;
    private Properties propServeur;
    boolean fini = false;
    public static FichierLog fichierLog;
    private LibrairieJDBC LibJDBC;
    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    
    public FenetreLogin(java.awt.Frame parent, boolean modal, JApplic_Chat fenetreclient, Socket SocketClient) {
        
        super(parent, modal);
        cliSock = SocketClient;
        initComponents();
        setTitle("Login de l'application de Home-Ferries");
        fenetreClient = fenetreclient;
        LibJDBC = new LibrairieJDBC();
        propServeur = LibJDBC.RecupPropertiesCompagnie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoutonQuitter = new javax.swing.JButton();
        Connect = new javax.swing.JButton();
        MotdePasse = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        TextFieldUsername = new javax.swing.JTextField();
        PanelMessageBienvenue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RetourValidationLogin = new javax.swing.JLabel();
        TextNumClient = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setMinimumSize(new java.awt.Dimension(610, 420));

        BoutonQuitter.setText("Quitter");
        BoutonQuitter.setMaximumSize(new java.awt.Dimension(0, 23));
        BoutonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonQuitterActionPerformed(evt);
            }
        });

        Connect.setText("Se connecter");
        Connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectActionPerformed(evt);
            }
        });

        MotdePasse.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        MotdePasse.setText("Numero Client :");

        Username.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Username.setText("Nom d'utilisateur :");

        PanelMessageBienvenue.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        PanelMessageBienvenue.setForeground(new java.awt.Color(0, 51, 204));
        PanelMessageBienvenue.setText("Panel d'identification sur Home-Ferries");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/header-image.jpg"))); // NOI18N

        RetourValidationLogin.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        RetourValidationLogin.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(PanelMessageBienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(TextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(MotdePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RetourValidationLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(TextNumClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Connect))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(BoutonQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(PanelMessageBienvenue)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(TextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MotdePasse)
                        .addComponent(TextNumClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Connect)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RetourValidationLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(BoutonQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BoutonQuitterActionPerformed

    private void ConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectActionPerformed
        System.out.println("1");
        RequeteFECOP req = null;
        ReponseFECOP reponse = null;
        
        if (this.TextFieldUsername.getText().equals("") && this.TextNumClient.getText().equals(""))
        {
            String msg;
            msg = "Un des deux champs est vide !";
            JOptionPane.showMessageDialog(this, msg, "Attention !", JOptionPane.INFORMATION_MESSAGE, null);
        }
        else
        {
            System.out.println("2");
            this.oos = null;
            this.ois = null;
            try 
            {
                System.out.println("10");
                cliSock = new Socket(propServeur.getProperty("adresse"), Integer.valueOf((String) propServeur.getProperty("portEcoute")));
                System.out.println("11");
                this.oos = new ObjectOutputStream(cliSock.getOutputStream());
                System.out.println("12");
                fenetreClient.oos = this.oos;
                System.out.println("13");
                this.ois = new ObjectInputStream(cliSock.getInputStream()); 
                fenetreClient.ois = this.ois;
                System.out.println("3");
                req = new RequeteFECOP(4, this.TextFieldUsername.getText(), this.TextNumClient.getText());

                this.oos.writeObject(req);
                System.out.println("Jenvoi la demande de connexion");

                System.out.println("4");
                reponse = (ReponseFECOP)this.ois.readObject();
                System.out.println("5");
                System.out.println("Reponse reçue : "+reponse.getCode());
                if (reponse.getCode() == 1)
                {
                    
                    fenetreClient.MenuSeConnecter.setEnabled(false);
                    fenetreClient.envoyer.setEnabled(true);
                    fenetreClient.input.setEnabled(true);
                    fenetreClient.connect.setEnabled(true);
                    fenetreClient.nomClient.setEnabled(true);
                    this.dispose();
                }
                else
                {
                    String msg;
                    msg = "Mot de passe invalide !";
                    JOptionPane.showMessageDialog(this, msg, "Attention !", JOptionPane.INFORMATION_MESSAGE, null);
                    this.TextFieldUsername.setText(""); 
                    this.TextNumClient.setText("");
                }
            } 
            catch (IOException e)
            { 
                System.err.println("Erreur réseau FenLogin ? [" + e.getMessage() + "]"); 
            } 
            catch (ClassNotFoundException ex)
            {
                Logger.getLogger(JApplic_Chat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ConnectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonQuitter;
    private javax.swing.JButton Connect;
    private javax.swing.JLabel MotdePasse;
    private javax.swing.JLabel PanelMessageBienvenue;
    private javax.swing.JLabel RetourValidationLogin;
    private javax.swing.JTextField TextFieldUsername;
    private javax.swing.JTextField TextNumClient;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
